### ISSUE TITLE
Error importing the list

### ISSUE THREAD

**Issue by asterismo** [Mastodon-DE/blocklists#14]
Hi, i'm Santiago from mastodon.uy, i cannot import the list. I get this error, any ideas?

Thanks!

`Error: Illegal quoting in line 1.`

**Comment by ErikUden** [comment]
Terribly sorry for this, I will get right to it.

**Comment by ErikUden** [comment]
Hmm, the import works for me with the newest commit! However, the quotation marks are not natural. They were added when someone from our team attempted to sort the domains alphabetically and the CSV program added them. To me, there was no harm with the quotes, but since it makes using the CSV file impossible to use for you, and for many others, I will remove the quotation marks!

**Comment by asterismo** [comment]
I'll try it, thanks!

**Comment by ErikUden** [comment]
I can import it on Mastodon v4.1.15 (troet.cafe) and v4.3.0 (mastodon.de). 

This is very odd - you're trying to import this file, right?

https://github.com/Mastodon-DE/blocklists/blob/main/spam/2024-02-15/2024-02-15-spam-domain_mutes-erik-uden.csv

**Comment by spirillen** [comment]
> I tried but it fails. It says it is a not valid CSV file. Actually i think it is not, since it opens up like a json file style structure, right? Libreoffice fails to open it as a regular CSV. I'm running Mastodon 4.2.7

Have you tested line endings?? lr vs crlf?
